### ISSUE TITLE
Home Page Layout

### ISSUE THREAD

**Issue by ericsims** [LetsBuildRockets/letsbuildrockets.github.io#1]
It would be great if we could make this look less... worse...  :)

**Comment by robstolarz** [comment]
I would just like to point out that iFrames are evil.
More seriously: the Facebook iframe cannot be larger than 500px. Google calendar should be set to Agenda mode on mobile, how do we do that, do we need a different app to handle it

**Comment by ericsims** [comment]
can we just set a attribute based on browser info? or do we want to do it the right way, with the screen size. Furthermore, we can pull the google calendar out of the iframe.

**Comment by robstolarz** [comment]
According to https://productforums.google.com/forum/#!topic/calendar/1pfBtuKsDFg you can change the URL for the embed for what you want (mode=AGENDA). So we would write JS that, if in mobile mode (check using modernizr), destroys the frame and makes a new one with mode=AGENDA set on the URL.

I don't actually think we can pull the GCal out of the frame, it's embedded based on a URL and we're not allowed to touch it AFAIK.

**Comment by ericsims** [comment]
Ah. Yeah I am working on it now I think it might look better if we just leave it as an agenda all the time. Ill let you know when I push.
