### ISSUE TITLE
Colon code isn’t parsed correctly by Facebook

### ISSUE THREAD

**Issue by TJScalzo** [LetsBuildRockets/letsbuildrockets.github.io#36]
The newest blog post was shared on Facebook but the metadata that it pulled from the page was interpreted literally. 
![img_4299](https://user-images.githubusercontent.com/15825214/29050626-309bb5a0-7bab-11e7-88a4-be64d114f722.PNG)
 I guess the solution would be to define the title some other way. Perhaps using a different designation for the colon character would work?

**Comment by gisellegk** [comment]
Yeah I saw that... Liquid didn't like having a colon in the metadata table
(front matter? Or something like that?) So I just slapped on a quick fix. I
wonder if there's a way to escape the character instead of encoding it like
that?? Or choosing a different encoding.

Also I think the page/tab title pulls from the same field so we should look
to see if the issue persists there too

**Comment by TJScalzo** [comment]
It seems like it's not an issue with the page title in Safari and in Chrome. 
<img width="437" alt="screen shot 2017-08-08 at 4 40 43 pm" src="https://user-images.githubusercontent.com/15825214/29093748-ed14b17a-7c58-11e7-9cea-b9735dc07714.png">
<img width="243" alt="screen shot 2017-08-08 at 4 41 33 pm" src="https://user-images.githubusercontent.com/15825214/29093750-ef87e486-7c58-11e7-8e64-8f074ce94231.png">

It seems like it's something specific to Facebook's method of pulling front matter/page metadata. I'll check if there's some documentation on how their link previews work.

**Comment by gisellegk** [comment]
After @TJScalzo 's fix, I did the following steps to fix this issue

1. Forced fb to re-scrape the info from the website using [this tool](https://developers.facebook.com/tools/debug/sharing/)
2. Went to the [facebook post](https://www.facebook.com/letsbuildrockets/posts/1837462356293921) and as admin, refreshed the share attachment.

Not sure if both steps are necessary but it's fixed now.
