### ISSUE TITLE
Color Changes

### ISSUE THREAD

**Issue by ericsims** [LetsBuildRockets/letsbuildrockets.github.io#4]
The rorange color needs to be changed to #F9423A everywhere. This includes the images in the footer. 

Also make the footer more legible

**Comment by ericsims** [comment]
We should also switch to SVGs for the logo and footer icons

**Comment by gisellegk** [comment]
We changed the footer icons to be gray instead of orange (but hover effect is #F9423A)

Images are still rasters, going to put that in a separate thread.
