### ISSUE TITLE
Rocketeer icons are ovals sometimes

### ISSUE THREAD

**Issue by ericsims** [LetsBuildRockets/letsbuildrockets.github.io#7]
On my android phone using chrome I have the following problems
- The pictures of the rocketeers appear oval instead of circular.

**Comment by robstolarz** [comment]
A screenshot: 

![screenshot_20161019-122655](https://cloud.githubusercontent.com/assets/3682844/19527784/5bc8882e-95f7-11e6-98a4-f369228faeca.png)

**Comment by robstolarz** [comment]
YES THANK YOU
